Development review build
ClovesPirate/Social-Media-Project pull request #1
Opened 2022-08-30 15:22 UTC by ClovesPirate

Implemented features as requested in the CA. The build is pretty barebone, and nothing beyond what has been requested has been worked on. Plenty of room for improvements on UX specifically and overall functionality - assuming we are to continue working on this project post-delivery.

Known issues: 
- Nav toggle needs improvements and better spacing.
- Posts under profile.html is not outputing the correct spacing on large screens.
- Code cleanup not finalized.

#Feedback:
- Would like feedback on spacing, particularly vertical spacing for both mobile and desktop.
- Is the overall design theme appropriate?
- Issues with code/bootstrap (better ways to write it).

2022-09-02 14:31 UTC, sulenchy commented on index.html
> +  <link rel="stylesheet" href="https://use.typekit.net/bqw8pcm.css">
To improve the SEO of this page, you can add a metadata for description

2022-09-02 15:13 UTC, sulenchy commented on login.html
>    <meta name="viewport" content="width=device-width, initial-scale=1.0">
You can add metadata for description here too

2022-09-02 15:15 UTC, sulenchy approved these changes
@ClovesPirate I left some comments concerning the description metadata.

2022-09-04 10:27 UTC, ClovesPirate commented
# To reviewer

The overall UI is pretty basic, as the assignment does not require a proper dashboard you'd expect from a social platform. Assuming we are to build upon this project a few things planned for the future for a better UX:
- Dashboard navigation on larger screen sizes/drawer for smaller screens.
- Modal/drawer chat functionality with easy access to friends.
- The ability to explore content and other users based on preference and interests.
- A more robust login page with more information provided to the potential user.

Otherwise it should be feature-complete as outlined in the assignment.

# changes
- Updated head to include a description for better SEO as requested by reviewer.
- Added .gitignore as per peer request
`- I used git in the console to add a .gitignore to my /node_modules using [this](https://sebhastian.com/git-ignore-node_modules/) tutorial, however it still appears in my text-editor, but it is grayed out. Not sure if I did it correctly. Feedback on what to do differently would be greatly appreciated it it is not working as intended.`

2022-09-04 21:03 UTC, sulenchy requested changes
The file changes are too much. This is a result of you pushing node_modules to GitHub. Please, do this to get that fixed

```
git rm -r --cached node_modules
git commit -m 'fix: remove node_modules from origin'
git push origin development
```

`git rm -r --cached node_modules` returns pathspec 'node_modules' did not match any files

2022-09-04 21:09 UTC, sulenchy requested changes
Please get rid of the node_modules

2022-09-04 22:00 UTC, sulenchy approved these changes
Looks good to me

2022-09-18 14:24 UTC, merged